name: "ci"
run-name: "build & test"

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: haskell:9.4
    steps:
      - uses: actions/checkout@v4
      - name: "Build"
        run: stack build
      - name: "Test"
        run: stack test
