name: "ci"
run-name: "build & test"

on: [push]

env:
  GH_TOKEN: ${{github.token}}

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4
      - name: "Install dependencies"
        run: |
          apt update
          apt install ghc haskell-stack -y
      - name: "Test"
        run: stack test
