name: "ci"
run-name: "build & test"

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4
      - name: "Install dependencies"
        run: |
          apt update
          apt install -y curl wget gnupg2 software-properties-common
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.8'
          enable-stack: true
          stack-version: 'latest'
      - name: "Build"
        run: stack build
      - name: "Test"
        run: stack test
